env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - tsconfig.json
    - tsconfig.eslint.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
root: true
rules:
  indent:
    - warn
    - 4
  "react/jsx-indent":
    - warn
    - 4
  "react/jsx-indent-props":
    - warn
    - 4
  "@typescript-eslint/no-unused-vars": warn
